### PR TITLE
nats: add publish function

### PR DESCRIPTION
**Pull request by eschmidbauer**
- move connections into separate struct
 - initiate global nats connection struct and use for subscribers and publishers

### CODE REVIEW

**Comment by eschmidbauer** [comment]
@smititelu i've been testing the publish change, It appears the publish connections will not stay connected without using a threading model.

**Comment by smititelu** [comment]
@eschmidbauer after how much time have you noticed that? It didn't happen to me in my basic testing so far.

Might be related to setting this 2 nats params?! Because I also noticed it won;t reconnect anymore beyond the retry limit (set by natsOptions_SetMaxReconnect()). However if you set it "-1" it will retry forever.

```
        natsOptions_SetMaxReconnect(c->opts, 10000);
        natsOptions_SetReconnectWait(c->opts, 2 * 1000);         // 2s

```

**Comment by smititelu** [comment]
@eschmidbauer also what I noticed after this PR:
```
$var(my_ci)=$ci + "|" + $fU + "|" + $ruri;
nats_publish("foo", $var(my_ci));
```
will print:
```
Nov 16 11:07:43 LXBU-GRPF8S2 kamailio: ERROR: <script>: ==============> received 0
```
instead of the actual variable content.

**Comment by eschmidbauer** [comment]
@smititelu try
nats_publish("foo", "$var(my_ci)");

**Comment by smititelu** [comment]
hi @eschmidbauer, If I try like that it will print:
```
Nov 24 10:29:25  kamailio: ERROR: <script>: ==============> received $var(my_ci)
```

**Comment by eschmidbauer** [comment]
```
$var(my_ci)="test";
nats_publish("foo", $var(my_ci));
```

Does this not work?

**Comment by smititelu** [comment]
Hi @eschmidbauer. Sorry for later reply:

For this config it prints:
```
$var(my_ci)="test";
nats_publish("foo", $var(my_ci));
---
Dec  6 09:44:52 LXBU-GRPF8S2 kamailio: ERROR: <script>: ==============> received 0
```

However for this config it prints:
```
nats_publish("foo", "test");
---
Dec  6 09:44:37 LXBU-GRPF8S2 kamailio: ERROR: <script>: ==============> received test
```

So i think there must be related to some $var() fixup?!

**Comment by eschmidbauer** [comment]
i suspect that is the case- it had never worked for me which made me wonder how it worked for you. 
You can reference other modules to see how PVs are passed to functions
Typically they are in quotes (e.g. `myfunc("$ru")`)

**Comment by smititelu** [comment]
my only idea is that it has something to do with function param order, i had a different order. Will check this probably next week.

**Comment by smititelu** [comment]
Hi, still didn't managed to find out why the $var() was not working.

However I've tried $dlg_var() and $avp() and they both worked as expected. IMHO, you should push this PR to upstream, and I will close my old PR.

Thank you,
Stefan

**Comment by eschmidbauer** [comment]
Can you rebase your changes onto latest master from upstream repo?

**Comment by smititelu** [comment]
done

**Comment by eschmidbauer** [comment]
i still see merge conflicts in the branch. i'd like to take your commit onto master and fixup the func so passing $var() works

**Comment by eschmidbauer** [comment]
i've pushed some big updates to test publishing [here](https://github.com/kamailio/kamailio/commit/3729f454f6d6739fb7511f29daed51ce2e8c8ef8)

still more cleanup needed but you should be able to publish with

```
$var(c) = "my payload";
nats_publish("mysub1", "This is $var(c)");
```

**Pull request closed without merging**
